const arrayProductos = [

{   id: 1,
    producto: "Expresso",
    categoria: "Café",
    descripcion: "Café tipo arábigo preparado con agua hirviendo en contacto con el grano recién molido y espuma por encima. Se presenta en envase de 300 ml",
    precio: 500,
    stock: 1000,
    imagen: "../../assets/cafeexpresso.jpg",
},

{   id: 2,
    producto: "Americano",
    categoria: "Café",
    descripcion: "Café similar al expresso pero con mayor cantidad de agua, lo que le confiere un sabor menos intenso y de un tenor menos amargo",
    precio: 500,
    stock: 1000,
    imagen: "../../assets/cafeamericano.jpg",
},

/*{   id: 3,
    producto: "Lungo",
    categoria: "Café",
    descripcion: "Café similar al expresso pero con mayor volumen. Se diferencia del americano en que no se agrega agua externa al expresso sino infusión",
    precio: 550,
    stock: 1000,
    imagen: "",
},

{   id: 4,
    producto: "Cortado",
    categoria: "Café",
    descripcion: "Café similar al expresso con el agregado de una pequeña cantidad de leche caliente que mancha al café",
    precio: 520,
    stock: 1000,
    imagen: "",
},

{   id: 5,
    producto: "Café con Leche",
    categoria: "Café",
    descripcion: "Café similar al cortado pero con un mayor agregado de leche, enproporción semejante a la de café. El sabor es más dulce y menos intenso que el del cortado pero sigue siendo importante la presencia de cafeína",
    precio: 580,
    stock: 1000,
    imagen: "",
},

{   id: 6,
    producto: "Bombón",
    categoria: "Café",
    descripcion: "Similar al café con leche pero el lácteo utilizado es leche condensada, lo que le confiere un sabor más dulce. La leche condensada se vierte primero para completar a continuación con el café de grano molido tipo arábigo",
    precio: 580,
    stock: 1000,
    imagen: "",
},

{   id: 7,
    producto: "Cappuccino",
    categoria: "Café",
    descripcion: "Café expresso con agregado de leche, siendo de un tercio la proporción del primero en forma aproximada. Se completa con crema de leche en la parte superior, caco en polvo y canela",
    precio: 650,
    stock: 1000,
    imagen: "",
},

{   id: 8,
    producto: "Vienés",
    categoria: "Café",
    descripcion: "Café expresso con agregado de crema de leche en menor proporción que el café",
    precio: 650,
    stock: 1000,
    imagen: "",
},

{   id: 9,
    producto: "Tentación",
    categoria: "Café",
    descripcion: "Café cappuccino con agregado de dulce de leche y salsa de chocolate disueltos",
    precio: 680,
    stock: 1000,
    imagen: "",
},

{   id: 10,
    producto: "Irlandés",
    categoria: "Café",
    descripcion: "Café lungo con agregado de whisky irlandés y una capa superior de crema de leche",
    precio: 750,
    stock: 1000,
    imagen: "",
},

{   id: 11,
    producto: "Frappé",
    categoria: "Café",
    descripcion: "Café frío elaborado en base a café instantáneo, hielo y una capa superior de crema de leche, con agregado de dulce de leche o salsa de chocolate, a elección",
    precio: 650,
    stock: 1000,
    imagen: "",
},*/

]

export default arrayProductos;


