const arrayProductos = [

{   id: 1,
    category: "Bebidas",
    producto: "Café",
    nombre: "Expresso",
    descripcion: "Café tipo arábigo preparado con agua hirviendo en contacto con el grano recién molido y espuma por encima. Se presenta en envase de 300 ml",
    precio: 500,
    stock: 1000,
    imagen: "/src/assets/cafeexpresso.jpg",
},

{   id: 2,
    category: "Bebidas",
    producto: "Café",
    nombre: "Americano",
    descripcion: "Café similar al expresso pero con mayor cantidad de agua, lo que le confiere un sabor menos intenso y de un tenor menos amargo",
    precio: 500,
    stock: 1000,
    imagen: "/src/assets/cafeamericano.jpg",
},

{   id: 3,
    category: "Bebidas",
    producto: "Café",
    nombre: "Lungo",
    descripcion: "Café similar al expresso pero con mayor volumen. Se diferencia del americano en que no se agrega agua externa al expresso sino infusión",
    precio: 550,
    stock: 1000,
    imagen: "/src/assets/cafelungo.jpg",
},

{   id: 4,
    category: "Bebidas",
    producto: "Café",
    nombre: "Cortado",
    descripcion: "Café similar al expresso con el agregado de una pequeña cantidad de leche caliente que mancha al café",
    precio: 520,
    stock: 1000,
    imagen: "/src/assets/cafecortado.jpg",
},

{   id: 5,
    category: "Bebidas",
    producto: "Café",
    nombre: "Con Leche",
    descripcion: "Café similar al cortado pero con un mayor agregado de leche, enproporción semejante a la de café. El sabor es más dulce y menos intenso que el del cortado pero sigue siendo importante la presencia de cafeína",
    precio: 580,
    stock: 1000,
    imagen: "/src/assets/cafeconleche.jpeg",
},

{   id: 6,
    category: "Bebidas",
    producto: "Café",
    nombre: "Bombón",
    descripcion: "Similar al café con leche pero el lácteo utilizado es leche condensada, lo que le confiere un sabor más dulce. La leche condensada se vierte primero para completar a continuación con el café de grano molido tipo arábigo. Se completa con una capa superior de espuma de leche y virutas de chocolate",
    precio: 580,
    stock: 1000,
    imagen: "/src/assets/cafebombon.jpg",
},

{   id: 7,
    category: "Bebidas",
    producto: "Café",
    nombre: "Cappuccino",
    descripcion: "Café expresso con agregado de leche, siendo de un tercio la proporción del primero en forma aproximada. Se completa con crema de leche en la parte superior, cacao en polvo y canela",
    precio: 650,
    stock: 1000,
    imagen: "/src/assets/cafecappuccino.jpg",
},

{   id: 8,
    category: "Bebidas",
    producto: "Café",
    nombre: "Vienés",
    descripcion: "Café expresso con agregado de crema de leche en menor proporción que el café",
    precio: 650,
    stock: 1000,
    imagen: "/src/assets/cafevienes.jpg",
},

{   id: 9,
    category: "Bebidas",
    producto: "Café",
    nombre: "Tentación",
    descripcion: "Café cappuccino con agregado de dulce de leche y salsa de chocolate disueltos",
    precio: 680,
    stock: 1000,
    imagen: "/src/assets/cafetentacion.jpg",
},

{   id: 10,
    category: "Bebidas",
    producto: "Café",
    nombre: "Irlandés",
    descripcion: "Café lungo con agregado de whisky irlandés y una capa superior de crema de leche",
    precio: 750,
    stock: 1000,
    imagen: "/src/assets/cafeirlandes.jpeg",
},

{   id: 11,
    category: "Bebidas",
    producto: "Café",
    nombre: "Frappé",
    descripcion: "Café frío elaborado en base a café instantáneo, hielo y una capa superior de crema de leche, con agregado de dulce de leche o salsa de chocolate, a elección",
    precio: 650,
    stock: 1000,
    imagen: "/src/assets/cafefrappe.jpg",
},

{   id: 12,
    category: "Bebidas",
    producto: "Café",
    nombre: "Azteca",
    descripcion: "Café frío elaborado en base a café instantáneo, hielo, crema de leche y dos bolas de helado de chocolate",
    precio: 620,
    stock: 1000,
    imagen: "/src/assets/cafeazteca.jpg",
},

{   id: 13,
    category: "Dulces",
    producto: "Medialuna",
    nombre: "Manteca",
    descripcion: "Triángulo panificado esponjoso elaborado en base a harina y manteca, cubierto con una capa de almíbar",
    precio: 120,
    stock: 1000,
    imagen: "/src/assets/medmanteca.jpg",
},

{   id: 14,
    category: "Dulces",
    producto: "Medialuna",
    nombre: "Grasa",
    descripcion: "Triángulo panificado crocante elaborado en base a harina y superficie ligeramente hojaldrada",
    precio: 120,
    stock: 1000,
    imagen: "/src/assets/medgrasa.jpg",
},

{   id: 15,
    category: "Dulces",
    producto: "Medialuna",
    nombre: "Rellena",
    descripcion: "Medialuna de manteca caliente, rellena con jamón cocido y queso",
    precio: 280,
    stock: 1000,
    imagen: "/src/assets/medrellenas.jpg",
},

{   id: 16,
    category: "Dulces",
    producto: "Alfajor",
    nombre: "Maicena",
    descripcion: "Producto elaborado con dos capas de almidón de maíz y relleno con dulde de leche, rebozado con coco",
    precio: 50,
    stock: 1000,
    imagen: "/src/assets/alfajmaicena.png",
},

{   id: 17,
    category: "Dulces",
    producto: "Alfajor",
    nombre: "Chocolate",
    descripcion: "Producto elaborado con harina, almidón de maíz, cacao y esencia de vainilla, con relleno de dulde de leche y una cubierta de chocolate negro",
    precio: 70,
    stock: 1000,
    imagen: "/src/assets/alfajchoc.jpg",
},

{   id: 18,
    category: "Dulces",
    producto: "Alfajor",
    nombre: "Blanco",
    descripcion: "Producto elaborado con harina, almidón de maíz, margarina y esencia de vainilla, con relleno de dulde de leche y una cubierta de chocolate blanco glaseado",
    precio: 70,
    stock: 1000,
    imagen: "/src/assets/alfajblanco.jpg",
},

{   id: 19,
    category: "Sandwiches",
    producto: "Sandwich",
    nombre: "Baguette",
    descripcion: "Un pan baguette con jamón cocido y queso en su interior, con una capa de mayonesa y aderezos a gusto",
    precio: 250,
    stock: 1000,
    imagen: "/src/assets/sandbaguettejyq.jpg",
},

{   id: 20,
    category: "Sandwiches",
    producto: "Sandwich",
    nombre: "Especial JyQ",
    descripcion: "Un pan tipo pebete con jamón cocido y queso en su interior y aderezos a gusto",
    precio: 250,
    stock: 1000,
    imagen: "/src/assets/sandpebetejyq.jpg",
},

{   id: 21,
    category: "Sandwiches",
    producto: "Sandwich",
    nombre: "Miga JyQ",
    descripcion: "Triple capa de pan de miga con jamón cocido y queso en su interior, aderezado con una lámina de mayonesa en cada capa",
    precio: 280,
    stock: 1000,
    imagen: "/src/assets/sandmigajyq.png",
},

{   id: 22,
    category: "Sandwiches",
    producto: "Sandwich",
    nombre: "Miga Triple",
    descripcion: "Triple capa de pan de miga con jamón cocido y un segundo producto a gusto en su interior, aderezado con una lámina de mayonesa en cada capa",
    precio: 350,
    stock: 1000,
    imagen: "/src/assets/sandmigaespeciales.jpg",
},

{   id: 23,
    category: "Sandwiches",
    producto: "Sandwich",
    nombre: "Tostado JyQ",
    descripcion: "Dos capas de pan de miga tostadas con jamón cocido y queso en su interior",
    precio: 320,
    stock: 1000,
    imagen: "/src/assets/sandtostadosjyq.jpg",
},
]

export default arrayProductos;


